# SPDX-FileCopyrightText: 2024 igniter contributors <https://github.com/ash-project/igniter/graphs/contributors>
#
# SPDX-License-Identifier: MIT

---
updates:
  - directory: /
    groups:
      all-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: git_ops
    package-ecosystem: mix
    schedule:
      interval: monthly
    versioning-strategy: lockfile-only
version: 2
